== Introduction

Pagero Universal Format, hereafter referred to as "PUF", is a business document specification developed and maintained by https://www.pagero.com[Pagero Group^]. 

PUF is based on https://docs.oasis-open.org/ubl/UBL-2.3.html[Universal Business Language version 2.3 (UBL 2.3)^].

Certain elements require the use of PUF specific code lists. Below you will find all these lists.

In the specification for each message/document type you will find an overview on where the different code lists are applicable.

In some of these code lists PUF only points towards an external code list to be used.

Other times the code list to be used is a mix between values defined specifically for PUF and other external list(s).

Lastly, in some cases, *all* the values are defined solely for PUF.

== Version and changelog

.Version
|===
|Version |Date |Description

|1.0 |2022-12-19 |First version published.
|1.1|2023-05-04|Added https://pagero.github.io/puf-code-lists/#_puf_020_errorclassificationcode[PUF-020-ERRORCLASSIFICATIONCODE^]
|1.2|2023-09-04|Updated https://pagero.github.io/puf-code-lists/#_puf_020_errorclassificationcode[PUF-020-ERRORCLASSIFICATIONCODE^]
|1.3|2024-06-18|Added Philippine specific codes. Rearrange https://pagero.github.io/puf-code-lists/#_puf_009_taxtypescheme[PUF-009-TAXTYPESCHEME^]
|===